# .streamlit/secrets.toml
openai_api_key = "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"
